# .streamlit/secrets.toml
openai_api_key = "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"
